# .streamlit/secrets.toml
openai_api_key = "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"
